apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: wanderlust
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: wanderlust-ebs
  resources:
    requests:
      storage: 5Gi
