apiVersion: v1
kind: Secret
metadata:
  name: wanderlust-secrets
  namespace: wanderlust
type: Opaque
stringData:
  # ⚠️ Use ArgoCD Vault Plugin or External Secrets Operator for production
  mongodb-uri: "mongodb://mongo-service:27017/wanderlust"
