apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wanderlust
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/shubhamsingh74888/wanderlust-gitops.git
    targetRevision: main
    path: kubernetes/production
  destination:
    server: https://kubernetes.default.svc
    namespace: wanderlust
  ignoreDifferences:
    - group: storage.k8s.io
      kind: StorageClass
      jsonPointers:
        - /provisioner
        - /parameters
        - /reclaimPolicy
        - /volumeBindingMode
        - /allowVolumeExpansion
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
